### PR TITLE
Change fiverr font

### PR DESCRIPTION
**Pull request by talw-fiverr**
moving to a new font instead of pluto

### CODE REVIEW

**Comment by michael5r** [comment]
So exciting.

**Comment by michael5r** [comment]
But shouldn't you actually be importing this font too? :)

**Comment by omrilotan** [comment]
The actual file is being included inV2 (asset pipeline). But we should consider an alternative

**Comment by lior-a** [comment]
It's super important to still provide both fonts for a some time - otherwise there are different repos that have old sass-assets and relay on pluto etc..

**Comment by michael5r** [comment]
@omrilotan My point was that we're loading Pluto using an @import statement in global-shared.scss - even though this PR changes the font-head variable to use Gotham instead of Pluto, it doesn't actually load the Gotham font anywhere.

**Comment by omrilotan** [comment]
1. The other repos won't be affected because they are pointing to a previous commit ID (think version). When they update sass-assets, they'll need to add the font.
2. A separate commit in V2 should update the commit ID for sass-assets as well as the import of the new font in place of the old.

**Comment by lior-a** [comment]
@omrilotan if you remove pluto from v2 and you have old version from sass-assets that point to pluto but w/o the pluto font - we'll end up with weird fonts combination which is why I suggested that both fonts should be available for some time.

if that was the plan than great - otherwise maybe i am missing something and we can take it offline.

**Pull request closed without merging**
